name: qoreh
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - fonts/

  fonts:
    - family: Josefin
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf
          style: normal
        - asset: fonts/JosefinSans-Bold.ttf
          weight: 700
        - asset: fonts/JosefinSans-Thin.ttf
          weight: 100
        - asset: fonts/JosefinSans-Light.ttf
          weight: 300
